import classNames from "classnames";
import {
    AcademicCapIcon,
    AdjustmentsHorizontalIcon,
    AdjustmentsVerticalIcon,
    ArchiveBoxArrowDownIcon,
    ArchiveBoxXMarkIcon,
    ArchiveBoxIcon,
    ArrowDownCircleIcon,
    ArrowDownLeftIcon,
    ArrowDownOnSquareIcon,
    ArrowDownOnSquareStackIcon,
    ArrowDownRightIcon,
    ArrowDownTrayIcon,
    ArrowDownIcon,
    ArrowLeftCircleIcon,
    ArrowLeftIcon,
    ArrowLongDownIcon,
    ArrowLongLeftIcon,
    ArrowLongRightIcon,
    ArrowLongUpIcon,
    ArrowPathRoundedSquareIcon,
    ArrowPathIcon,
    ArrowRightCircleIcon,
    ArrowRightIcon,
    ArrowTopRightOnSquareIcon,
    ArrowTrendingDownIcon,
    ArrowTrendingUpIcon,
    ArrowUpCircleIcon,
    ArrowUpLeftIcon,
    ArrowUpOnSquareIcon,
    ArrowUpOnSquareStackIcon,
    ArrowUpRightIcon,
    ArrowUpTrayIcon,
    ArrowUpIcon,
    ArrowUturnDownIcon,
    ArrowUturnLeftIcon,
    ArrowUturnRightIcon,
    ArrowUturnUpIcon,
    ArrowsPointingInIcon,
    ArrowsPointingOutIcon,
    ArrowsRightLeftIcon,
    ArrowsUpDownIcon,
    AtSymbolIcon,
    BackspaceIcon,
    BackwardIcon,
    BanknotesIcon,
    Bars2Icon,
    Bars3BottomLeftIcon,
    Bars3BottomRightIcon,
    Bars3CenterLeftIcon,
    Bars3Icon,
    Bars4Icon,
    BarsArrowDownIcon,
    BarsArrowUpIcon,
    BeakerIcon,
    BellAlertIcon,
    BellSlashIcon,
    BellSnoozeIcon,
    BellIcon,
    BoltSlashIcon,
    BoltIcon,
    BookOpenIcon,
    BookmarkSlashIcon,
    BookmarkSquareIcon,
    BookmarkIcon,
    BriefcaseIcon,
    BugAntIcon,
    BuildingLibraryIcon,
    BuildingOffice2Icon,
    BuildingOfficeIcon,
    BuildingStorefrontIcon,
    CakeIcon,
    CalculatorIcon,
    CalendarDaysIcon,
    CalendarIcon,
    CameraIcon,
    ChartBarSquareIcon,
    ChartBarIcon,
    ChartPieIcon,
    ChatBubbleBottomCenterIcon,
    ChatBubbleBottomCenterTextIcon,
    ChatBubbleLeftEllipsisIcon,
    ChatBubbleLeftRightIcon,
    ChatBubbleLeftIcon,
    ChatBubbleOvalLeftEllipsisIcon,
    ChatBubbleOvalLeftIcon,
    CheckBadgeIcon,
    CheckCircleIcon,
    CheckIcon,
    ChevronDoubleDownIcon,
    ChevronDoubleLeftIcon,
    ChevronDoubleRightIcon,
    ChevronDoubleUpIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpDownIcon,
    ChevronUpIcon,
    CircleStackIcon,
    ClipboardDocumentCheckIcon,
    ClipboardDocumentListIcon,
    ClipboardDocumentIcon,
    ClipboardIcon,
    ClockIcon,
    CloudArrowDownIcon,
    CloudArrowUpIcon,
    CloudIcon,
    CodeBracketSquareIcon,
    CodeBracketIcon,
    Cog6ToothIcon,
    Cog8ToothIcon,
    CogIcon,
    CommandLineIcon,
    ComputerDesktopIcon,
    CpuChipIcon,
    CreditCardIcon,
    CubeTransparentIcon,
    CubeIcon,
    CurrencyBangladeshiIcon,
    CurrencyDollarIcon,
    CurrencyEuroIcon,
    CurrencyPoundIcon,
    CurrencyRupeeIcon,
    CurrencyYenIcon,
    CursorArrowRaysIcon,
    CursorArrowRippleIcon,
    DevicePhoneMobileIcon,
    DeviceTabletIcon,
    DocumentArrowDownIcon,
    DocumentArrowUpIcon,
    DocumentChartBarIcon,
    DocumentCheckIcon,
    DocumentDuplicateIcon,
    DocumentMagnifyingGlassIcon,
    DocumentMinusIcon,
    DocumentPlusIcon,
    DocumentTextIcon,
    DocumentIcon,
    EllipsisHorizontalCircleIcon,
    EllipsisHorizontalIcon,
    EllipsisVerticalIcon,
    EnvelopeOpenIcon,
    EnvelopeIcon,
    ExclamationCircleIcon,
    ExclamationTriangleIcon,
    EyeDropperIcon,
    EyeSlashIcon,
    EyeIcon,
    FaceFrownIcon,
    FaceSmileIcon,
    FilmIcon,
    FingerPrintIcon,
    FireIcon,
    FlagIcon,
    FolderArrowDownIcon,
    FolderMinusIcon,
    FolderOpenIcon,
    FolderPlusIcon,
    FolderIcon,
    ForwardIcon,
    FunnelIcon,
    GifIcon,
    GiftTopIcon,
    GiftIcon,
    GlobeAltIcon,
    GlobeAmericasIcon,
    GlobeAsiaAustraliaIcon,
    GlobeEuropeAfricaIcon,
    HandRaisedIcon,
    HandThumbDownIcon,
    HandThumbUpIcon,
    HashtagIcon,
    HeartIcon,
    HomeModernIcon,
    HomeIcon,
    IdentificationIcon,
    InboxArrowDownIcon,
    InboxStackIcon,
    InboxIcon,
    InformationCircleIcon,
    KeyIcon,
    LanguageIcon,
    LifebuoyIcon,
    LightBulbIcon,
    LinkIcon,
    ListBulletIcon,
    LockClosedIcon,
    LockOpenIcon,
    MagnifyingGlassCircleIcon,
    MagnifyingGlassMinusIcon,
    MagnifyingGlassPlusIcon,
    MagnifyingGlassIcon,
    MapPinIcon,
    MapIcon,
    MegaphoneIcon,
    MicrophoneIcon,
    MinusCircleIcon,
    MinusIcon,
    MoonIcon,
    MusicalNoteIcon,
    NewspaperIcon,
    NoSymbolIcon,
    PaintBrushIcon,
    PaperAirplaneIcon,
    PaperClipIcon,
    PauseCircleIcon,
    PauseIcon,
    PencilSquareIcon,
    PencilIcon,
    PhoneArrowDownLeftIcon,
    PhoneArrowUpRightIcon,
    PhoneXMarkIcon,
    PhoneIcon,
    PhotoIcon,
    PlayCircleIcon,
    PlayPauseIcon,
    PlayIcon,
    PlusCircleIcon,
    PlusSmallIcon,
    PlusIcon,
    PowerIcon,
    PresentationChartBarIcon,
    PresentationChartLineIcon,
    PrinterIcon,
    PuzzlePieceIcon,
    QrCodeIcon,
    QuestionMarkCircleIcon,
    QueueListIcon,
    RadioIcon,
    ReceiptPercentIcon,
    ReceiptRefundIcon,
    RectangleGroupIcon,
    RectangleStackIcon,
    RocketLaunchIcon,
    RssIcon,
    ScaleIcon,
    ScissorsIcon,
    ServerStackIcon,
    ServerIcon,
    ShareIcon,
    ShieldCheckIcon,
    ShieldExclamationIcon,
    ShoppingBagIcon,
    ShoppingCartIcon,
    SignalSlashIcon,
    SignalIcon,
    SparklesIcon,
    SpeakerWaveIcon,
    SpeakerXMarkIcon,
    Square2StackIcon,
    Square3Stack3DIcon,
    Squares2X2Icon,
    SquaresPlusIcon,
    StarIcon,
    StopCircleIcon,
    StopIcon,
    SunIcon,
    SwatchIcon,
    TableCellsIcon,
    TagIcon,
    TicketIcon,
    TrashIcon,
    TrophyIcon,
    TruckIcon,
    TvIcon,
    UserCircleIcon,
    UserGroupIcon,
    UserMinusIcon,
    UserPlusIcon,
    UserIcon,
    UsersIcon,
    VariableIcon,
    VideoCameraSlashIcon,
    VideoCameraIcon,
    ViewColumnsIcon,
    ViewfinderCircleIcon,
    WalletIcon,
    WifiIcon,
    WindowIcon,
    WrenchScrewdriverIcon,
    WrenchIcon,
    XCircleIcon,
    XMarkIcon,
} from "@heroicons/react/24/solid";

const iconMap = {
    "academic-cap": AcademicCapIcon,
    "adjustments-horizontal": AdjustmentsHorizontalIcon,
    "adjustments-vertical": AdjustmentsVerticalIcon,
    "archive-box-arrow-down": ArchiveBoxArrowDownIcon,
    "archive-box-x-mark": ArchiveBoxXMarkIcon,
    "archive-box": ArchiveBoxIcon,
    "arrow-down-circle": ArrowDownCircleIcon,
    "arrow-down-left": ArrowDownLeftIcon,
    "arrow-down-on-square": ArrowDownOnSquareIcon,
    "arrow-down-on-square-stack": ArrowDownOnSquareStackIcon,
    "arrow-down-right": ArrowDownRightIcon,
    "arrow-down-tray": ArrowDownTrayIcon,
    "arrow-down": ArrowDownIcon,
    "arrow-left-circle": ArrowLeftCircleIcon,
    "arrow-left": ArrowLeftIcon,
    "arrow-long-down": ArrowLongDownIcon,
    "arrow-long-left": ArrowLongLeftIcon,
    "arrow-long-right": ArrowLongRightIcon,
    "arrow-long-up": ArrowLongUpIcon,
    "arrow-path-rounded-square": ArrowPathRoundedSquareIcon,
    "arrow-path": ArrowPathIcon,
    "arrow-right-circle": ArrowRightCircleIcon,
    "arrow-right": ArrowRightIcon,
    "arrow-top-right-on-square": ArrowTopRightOnSquareIcon,
    "arrow-trending-down": ArrowTrendingDownIcon,
    "arrow-trending-up": ArrowTrendingUpIcon,
    "arrow-up-circle": ArrowUpCircleIcon,
    "arrow-up-left": ArrowUpLeftIcon,
    "arrow-up-on-square": ArrowUpOnSquareIcon,
    "arrow-up-on-square-stack": ArrowUpOnSquareStackIcon,
    "arrow-up-right": ArrowUpRightIcon,
    "arrow-up-tray": ArrowUpTrayIcon,
    "arrow-up": ArrowUpIcon,
    "arrow-uturn-down": ArrowUturnDownIcon,
    "arrow-uturn-left": ArrowUturnLeftIcon,
    "arrow-uturn-right": ArrowUturnRightIcon,
    "arrow-uturn-up": ArrowUturnUpIcon,
    "arrows-pointing-in": ArrowsPointingInIcon,
    "arrows-pointing-out": ArrowsPointingOutIcon,
    "arrows-right-left": ArrowsRightLeftIcon,
    "arrows-up-down": ArrowsUpDownIcon,
    "at-symbol": AtSymbolIcon,
    "backspace": BackspaceIcon,
    "backward": BackwardIcon,
    "banknotes": BanknotesIcon,
    "bars-2": Bars2Icon,
    "bars-3-bottom-left": Bars3BottomLeftIcon,
    "bars-3-bottom-right": Bars3BottomRightIcon,
    "bars-3-center-left": Bars3CenterLeftIcon,
    "bars-3": Bars3Icon,
    "bars-4": Bars4Icon,
    "bars-arrow-down": BarsArrowDownIcon,
    "bars-arrow-up": BarsArrowUpIcon,
    "beaker": BeakerIcon,
    "bell-alert": BellAlertIcon,
    "bell-slash": BellSlashIcon,
    "bell-snooze": BellSnoozeIcon,
    "bell": BellIcon,
    "bolt-slash": BoltSlashIcon,
    "bolt": BoltIcon,
    "book-open": BookOpenIcon,
    "bookmark-slash": BookmarkSlashIcon,
    "bookmark-square": BookmarkSquareIcon,
    "bookmark": BookmarkIcon,
    "briefcase": BriefcaseIcon,
    "bug-ant": BugAntIcon,
    "building-library": BuildingLibraryIcon,
    "building-office-2": BuildingOffice2Icon,
    "building-office": BuildingOfficeIcon,
    "building-storefront": BuildingStorefrontIcon,
    "cake": CakeIcon,
    "calculator": CalculatorIcon,
    "calendar-days": CalendarDaysIcon,
    "calendar": CalendarIcon,
    "camera": CameraIcon,
    "chart-bar-square": ChartBarSquareIcon,
    "chart-bar": ChartBarIcon,
    "chart-pie": ChartPieIcon,
    "chat-bubble-bottom-center": ChatBubbleBottomCenterIcon,
    "chat-bubble-bottom-center-text": ChatBubbleBottomCenterTextIcon,
    "chat-bubble-left-ellipsis": ChatBubbleLeftEllipsisIcon,
    "chat-bubble-left-right": ChatBubbleLeftRightIcon,
    "chat-bubble-left": ChatBubbleLeftIcon,
    "chat-bubble-oval-left-ellipsis": ChatBubbleOvalLeftEllipsisIcon,
    "chat-bubble-oval-left": ChatBubbleOvalLeftIcon,
    "check-badge": CheckBadgeIcon,
    "check-circle": CheckCircleIcon,
    "check": CheckIcon,
    "chevron-double-down": ChevronDoubleDownIcon,
    "chevron-double-left": ChevronDoubleLeftIcon,
    "chevron-double-right": ChevronDoubleRightIcon,
    "chevron-double-up": ChevronDoubleUpIcon,
    "chevron-down": ChevronDownIcon,
    "chevron-left": ChevronLeftIcon,
    "chevron-right": ChevronRightIcon,
    "chevron-up-down": ChevronUpDownIcon,
    "chevron-up": ChevronUpIcon,
    "circle-stack": CircleStackIcon,
    "clipboard-document-check": ClipboardDocumentCheckIcon,
    "clipboard-document-list": ClipboardDocumentListIcon,
    "clipboard-document": ClipboardDocumentIcon,
    "clipboard": ClipboardIcon,
    "clock": ClockIcon,
    "cloud-arrow-down": CloudArrowDownIcon,
    "cloud-arrow-up": CloudArrowUpIcon,
    "cloud": CloudIcon,
    "code-bracket-square": CodeBracketSquareIcon,
    "code-bracket": CodeBracketIcon,
    "cog-6-tooth": Cog6ToothIcon,
    "cog-8-tooth": Cog8ToothIcon,
    "cog": CogIcon,
    "command-line": CommandLineIcon,
    "computer-desktop": ComputerDesktopIcon,
    "cpu-chip": CpuChipIcon,
    "credit-card": CreditCardIcon,
    "cube-transparent": CubeTransparentIcon,
    "cube": CubeIcon,
    "currency-bangladeshi": CurrencyBangladeshiIcon,
    "currency-dollar": CurrencyDollarIcon,
    "currency-euro": CurrencyEuroIcon,
    "currency-pound": CurrencyPoundIcon,
    "currency-rupee": CurrencyRupeeIcon,
    "currency-yen": CurrencyYenIcon,
    "cursor-arrow-rays": CursorArrowRaysIcon,
    "cursor-arrow-ripple": CursorArrowRippleIcon,
    "device-phone-mobile": DevicePhoneMobileIcon,
    "device-tablet": DeviceTabletIcon,
    "document-arrow-down": DocumentArrowDownIcon,
    "document-arrow-up": DocumentArrowUpIcon,
    "document-chart-bar": DocumentChartBarIcon,
    "document-check": DocumentCheckIcon,
    "document-duplicate": DocumentDuplicateIcon,
    "document-magnifying-glass": DocumentMagnifyingGlassIcon,
    "document-minus": DocumentMinusIcon,
    "document-plus": DocumentPlusIcon,
    "document-text": DocumentTextIcon,
    "document": DocumentIcon,
    "ellipsis-horizontal-circle": EllipsisHorizontalCircleIcon,
    "ellipsis-horizontal": EllipsisHorizontalIcon,
    "ellipsis-vertical": EllipsisVerticalIcon,
    "envelope-open": EnvelopeOpenIcon,
    "envelope": EnvelopeIcon,
    "exclamation-circle": ExclamationCircleIcon,
    "exclamation-triangle": ExclamationTriangleIcon,
    "eye-dropper": EyeDropperIcon,
    "eye-slash": EyeSlashIcon,
    "eye": EyeIcon,
    "face-frown": FaceFrownIcon,
    "face-smile": FaceSmileIcon,
    "film": FilmIcon,
    "finger-print": FingerPrintIcon,
    "fire": FireIcon,
    "flag": FlagIcon,
    "folder-arrow-down": FolderArrowDownIcon,
    "folder-minus": FolderMinusIcon,
    "folder-open": FolderOpenIcon,
    "folder-plus": FolderPlusIcon,
    "folder": FolderIcon,
    "forward": ForwardIcon,
    "funnel": FunnelIcon,
    "gif": GifIcon,
    "gift-top": GiftTopIcon,
    "gift": GiftIcon,
    "globe-alt": GlobeAltIcon,
    "globe-americas": GlobeAmericasIcon,
    "globe-asia-australia": GlobeAsiaAustraliaIcon,
    "globe-europe-africa": GlobeEuropeAfricaIcon,
    "hand-raised": HandRaisedIcon,
    "hand-thumb-down": HandThumbDownIcon,
    "hand-thumb-up": HandThumbUpIcon,
    "hashtag": HashtagIcon,
    "heart": HeartIcon,
    "home-modern": HomeModernIcon,
    "home": HomeIcon,
    "identification": IdentificationIcon,
    "inbox-arrow-down": InboxArrowDownIcon,
    "inbox-stack": InboxStackIcon,
    "inbox": InboxIcon,
    "information-circle": InformationCircleIcon,
    "key": KeyIcon,
    "language": LanguageIcon,
    "lifebuoy": LifebuoyIcon,
    "light-bulb": LightBulbIcon,
    "link": LinkIcon,
    "list-bullet": ListBulletIcon,
    "lock-closed": LockClosedIcon,
    "lock-open": LockOpenIcon,
    "magnifying-glass-circle": MagnifyingGlassCircleIcon,
    "magnifying-glass-minus": MagnifyingGlassMinusIcon,
    "magnifying-glass-plus": MagnifyingGlassPlusIcon,
    "magnifying-glass": MagnifyingGlassIcon,
    "map-pin": MapPinIcon,
    "map": MapIcon,
    "megaphone": MegaphoneIcon,
    "microphone": MicrophoneIcon,
    "minus-circle": MinusCircleIcon,
    "minus": MinusIcon,
    "moon": MoonIcon,
    "musical-note": MusicalNoteIcon,
    "newspaper": NewspaperIcon,
    "no-symbol": NoSymbolIcon,
    "paint-brush": PaintBrushIcon,
    "paper-airplane": PaperAirplaneIcon,
    "paper-clip": PaperClipIcon,
    "pause-circle": PauseCircleIcon,
    "pause": PauseIcon,
    "pencil-square": PencilSquareIcon,
    "pencil": PencilIcon,
    "phone-arrow-down-left": PhoneArrowDownLeftIcon,
    "phone-arrow-up-right": PhoneArrowUpRightIcon,
    "phone-x-mark": PhoneXMarkIcon,
    "phone": PhoneIcon,
    "photo": PhotoIcon,
    "play-circle": PlayCircleIcon,
    "play-pause": PlayPauseIcon,
    "play": PlayIcon,
    "plus-circle": PlusCircleIcon,
    "plus-small": PlusSmallIcon,
    "plus": PlusIcon,
    "power": PowerIcon,
    "presentation-chart-bar": PresentationChartBarIcon,
    "presentation-chart-line": PresentationChartLineIcon,
    "printer": PrinterIcon,
    "puzzle-piece": PuzzlePieceIcon,
    "qr-code": QrCodeIcon,
    "question-mark-circle": QuestionMarkCircleIcon,
    "queue-list": QueueListIcon,
    "radio": RadioIcon,
    "receipt-percent": ReceiptPercentIcon,
    "receipt-refund": ReceiptRefundIcon,
    "rectangle-group": RectangleGroupIcon,
    "rectangle-stack": RectangleStackIcon,
    "rocket-launch": RocketLaunchIcon,
    "rss": RssIcon,
    "scale": ScaleIcon,
    "scissors": ScissorsIcon,
    "server-stack": ServerStackIcon,
    "server": ServerIcon,
    "share": ShareIcon,
    "shield-check": ShieldCheckIcon,
    "shield-exclamation": ShieldExclamationIcon,
    "shopping-bag": ShoppingBagIcon,
    "shopping-cart": ShoppingCartIcon,
    "signal-slash": SignalSlashIcon,
    "signal": SignalIcon,
    "sparkles": SparklesIcon,
    "speaker-wave": SpeakerWaveIcon,
    "speaker-x-mark": SpeakerXMarkIcon,
    "square-2-stack": Square2StackIcon,
    "square-3-stack-3d": Square3Stack3DIcon,
    "squares-2x2": Squares2X2Icon,
    "squares-plus": SquaresPlusIcon,
    "star": StarIcon,
    "stop-circle": StopCircleIcon,
    "stop": StopIcon,
    "sun": SunIcon,
    "swatch": SwatchIcon,
    "table-cells": TableCellsIcon,
    "tag": TagIcon,
    "ticket": TicketIcon,
    "trash": TrashIcon,
    "trophy": TrophyIcon,
    "truck": TruckIcon,
    "tv": TvIcon,
    "user-circle": UserCircleIcon,
    "user-group": UserGroupIcon,
    "user-minus": UserMinusIcon,
    "user-plus": UserPlusIcon,
    "user": UserIcon,
    "users": UsersIcon,
    "variable": VariableIcon,
    "video-camera-slash": VideoCameraSlashIcon,
    "video-camera": VideoCameraIcon,
    "view-columns": ViewColumnsIcon,
    "viewfinder-circle": ViewfinderCircleIcon,
    "wallet": WalletIcon,
    "wifi": WifiIcon,
    "window": WindowIcon,
    "wrench-screwdriver": WrenchScrewdriverIcon,
    "wrench": WrenchIcon,
    "x-circle": XCircleIcon,
    "x-mark": XMarkIcon,
} as const;

type IconSize = "xs" | "sm" | "md" | "lg" | "xl" | "2xl";

type IconLibraryProps = {
    name: keyof typeof iconMap ;
    size?: IconSize;
    className?: string;
};

const sizeClasses: Record<IconSize, string> = {
    xs: "size-3",
    sm: "size-4",
    md: "size-5",
    lg: "size-6",
    xl: "size-8",
    "2xl": "size-10",
};

export default function IconLibrary({ name, size = "sm", className = "" }: IconLibraryProps) {
    const IconComponent = iconMap[name];

    if (!IconComponent) {
        console.warn(`Icon "${name}" not found in icon map`);
        return null;
    }

    return (
        <IconComponent
            className={classNames(
                sizeClasses[size],
                className
            )}
        />
    );
}